# Generated by Django 3.1.1 on 2022-10-27 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20221027_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.IntegerField(default='071234567', help_text='Enter 10 digits phone number', unique=True, verbose_name='Phone Number'),
        ),
    ]
