# Generated by Django 3.1.1 on 2022-11-01 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20221027_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(default='254712345678', help_text='Enter 10 digits phone number', max_length=12, unique=True, verbose_name='Phone Number'),
        ),
    ]
